export class CharacterDashboradDto {
    ID: number;
    CharacterName: string;
    Level: number;
    Conscious: boolean;
    Alive: boolean;
    MaxHealth: number;
    CurrentHealth: number;
    ArmorClass: number;
    Strength: number;
    StrengthModifier: number;
    Dexterity: number;
    DexterityModifier: number;
    Constitution: number;
    ConstitutionModifier: number;
    Intelligence: number;
    IntelligenceModifier: number;
    Wisdom: number;
    WisdomModifier: number;
    Charisma: number;
    CharismaModifier: number;
    ProficiencyBonus: number;
    Speed: number;
    Copper: number;
    Silver: number;
    Gold: number;
    MaxHitDice: number;
    CurrentHitDice: number;
    RaceName: string;
    // CharacterClassName: string;
    // CampaignName: number;
    // PlayerName: number;
}