# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Orins Gate Stats

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-api:
    runs-on: windows-latest
    env:
      working-directory: ./OrinsGateStats.API

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'
        
    - name: echo pwd
      run: pwd
      shell: pwsh
    
    - name: echo working directory
      run: pwd
      working-directory: ${{ env.working-directory }}
      shell: pwsh
        
    - name: Create environment File
      run: |
        del envrionment.ts
        mv envrionment.prod.ts environment.ts
      shell: pwsh
      working-directory: ./OrinsGateStats.API/Source/Environment
    
    - name: Find and Replace Database URL
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: 'DATABASE_URL'
        replace: ${{ secrets.DATABASE_URL }}
        
    - name: Find and Replace JWT Secret
      uses: jacobtomlinson/gha-find-replace@0.1.1
      with:
        find: 'JWT_SECRET'
        replace: ${{ secrets.JWT_SECRET }}

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ${{ env.working-directory }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'orinsgatestatsapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a84690b167e04b9d98da3632bc044a8c }}
        package:  ${{ env.working-directory }}

  build-and-deploy-client:
    runs-on: windows-latest
    env:
      working-directory: ./OrinsGateStats.Client.Angular
      
    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'
    
    - name: npm install, build, and test
      run: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      working-directory: ${{ env.working-directory }}
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'orinsgatestats'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7af393f40ef24a1489ae5e87c0720985 }}
        package: ${{ env.working-directory }}/dist/orins-gate/stats
